# Generated by Django 6.0.4 on 2026-04-14 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='disciplina_substituta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes_disciplina', to='gestao.disciplina'),
        ),
        migrations.AlterField(
            model_name='gradehoraria',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.disciplina'),
        ),
        migrations.AlterField(
            model_name='gradehoraria',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.professor'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='tipo',
            field=models.CharField(choices=[('P', 'Permuta'), ('S', 'Substituição Direta'), ('L', 'Liberação (Deixar em branco)'), ('A', 'Assumir Horário (Preencher branco)')], max_length=1),
        ),
    ]
