# Generated by Django 6.0.4 on 2026-04-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_solicitacao_disciplina_substituta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='turno',
            field=models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino'), ('N', 'Noturno')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='turma',
            name='horarios_permitidos',
            field=models.ManyToManyField(blank=True, related_name='turmas_permitidas', to='gestao.horario'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia_semana',
            field=models.IntegerField(),
        ),
    ]
