# Generated by Django 6.0.4 on 2026-04-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_alter_horario_dia_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='carater',
            field=models.CharField(choices=[('T', 'Temporário (Apenas nesta data)'), ('D', 'Definitivo (Restante do período)')], default='T', max_length=1),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='tipo',
            field=models.CharField(choices=[('P', 'Permuta'), ('S', 'Substituição Direta'), ('L', 'Liberação'), ('A', 'Assumir')], max_length=1),
        ),
    ]
