# Generated by Django 6.0.4 on 2026-04-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_solicitacao_carater_alter_solicitacao_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaNaoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data do feriado, recesso ou conselho de classe.', unique=True)),
                ('descricao', models.CharField(help_text='Ex: Feriado Nacional, Recesso Escolar, etc.', max_length=100)),
                ('turmas_afetadas', models.ManyToManyField(blank=True, help_text='Deixe em branco para aplicar a toda a instituição.', to='gestao.turma')),
            ],
        ),
    ]
