# Generated by Django 6.0.4 on 2026-04-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_professor_matricula_alter_professor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='quantidade_aulas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
