# Generated by Django 6.0.4 on 2026-04-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_disciplina_quantidade_aulas'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='is_diretor',
            field=models.BooleanField(default=False),
        ),
    ]
