# Generated by Django 6.0.4 on 2026-04-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_professor_is_diretor'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='data_devolucao',
            field=models.DateField(blank=True, help_text='Data em que a aula será devolvida (se já estiver combinada)', null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='devolucao_pendente',
            field=models.BooleanField(default=False, help_text='Marca se o professor ficou devendo esta aula para o substituto'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='data_aplicacao',
            field=models.DateField(help_text='Data específica em que a ausência/troca inicial ocorrerá'),
        ),
    ]
