# Generated by Django 6.0.4 on 2026-05-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_solicitacao_data_devolucao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradehoraria',
            name='professor',
        ),
        migrations.AddField(
            model_name='gradehoraria',
            name='professores',
            field=models.ManyToManyField(blank=True, related_name='grades_horarias', to='gestao.professor'),
        ),
    ]
